-- Tripmate 多人共享数据初始化脚本
-- 在 Supabase 项目左侧打开 SQL Editor，粘贴整份脚本，然后点击 Run。

create table if not exists public.shared_expenses (
  id bigint generated by default as identity primary key,
  trip_code text not null default 'SEOUL630',
  title text not null,
  amount numeric(12, 2) not null check (amount > 0),
  payer text not null,
  category text not null check (category in ('lodging', 'food', 'transport', 'fun')),
  participants text[] not null,
  created_at timestamptz not null default now()
);

alter table public.shared_expenses enable row level security;
alter table public.shared_expenses replica identity full;

drop policy if exists "Anyone can view shared trip expenses" on public.shared_expenses;
create policy "Anyone can view shared trip expenses"
on public.shared_expenses for select
to anon, authenticated
using (trip_code = 'SEOUL630');

drop policy if exists "Anyone can add shared trip expenses" on public.shared_expenses;
create policy "Anyone can add shared trip expenses"
on public.shared_expenses for insert
to anon, authenticated
with check (
  trip_code = 'SEOUL630'
  and payer in ('lulu', 'jiajia', 'xiaobei', 'ahuang', 'momo', 'anan')
  and cardinality(participants) > 0
);

drop policy if exists "Anyone can delete shared trip expenses" on public.shared_expenses;
create policy "Anyone can delete shared trip expenses"
on public.shared_expenses for delete
to anon, authenticated
using (trip_code = 'SEOUL630');

create table if not exists public.shared_plans (
  id bigint generated by default as identity primary key,
  trip_code text not null default 'SEOUL630',
  day_index integer not null check (day_index between 0 and 4),
  plan_time text not null,
  title text not null,
  detail text not null default '',
  icon text not null default '行',
  participants text[] not null,
  created_by text not null,
  created_at timestamptz not null default now()
);

alter table public.shared_plans enable row level security;
alter table public.shared_plans replica identity full;

drop policy if exists "Anyone can view shared trip plans" on public.shared_plans;
create policy "Anyone can view shared trip plans"
on public.shared_plans for select
to anon, authenticated
using (trip_code = 'SEOUL630');

drop policy if exists "Anyone can add shared trip plans" on public.shared_plans;
create policy "Anyone can add shared trip plans"
on public.shared_plans for insert
to anon, authenticated
with check (
  trip_code = 'SEOUL630'
  and day_index between 0 and 4
  and created_by in ('lulu', 'jiajia', 'xiaobei', 'ahuang', 'momo', 'anan')
  and cardinality(participants) > 0
);

drop policy if exists "Anyone can delete shared trip plans" on public.shared_plans;
create policy "Anyone can delete shared trip plans"
on public.shared_plans for delete
to anon, authenticated
using (trip_code = 'SEOUL630');

create table if not exists public.shared_rooms (
  id bigint generated by default as identity primary key,
  trip_code text not null default 'SEOUL630',
  room_number text not null,
  room_type text not null,
  room_detail text not null,
  members text[] not null default '{}',
  updated_at timestamptz not null default now(),
  unique (trip_code, room_number)
);

alter table public.shared_rooms enable row level security;
alter table public.shared_rooms replica identity full;

drop policy if exists "Anyone can view shared rooms" on public.shared_rooms;
create policy "Anyone can view shared rooms"
on public.shared_rooms for select to anon, authenticated
using (trip_code = 'SEOUL630');

drop policy if exists "Anyone can add shared rooms" on public.shared_rooms;
create policy "Anyone can add shared rooms"
on public.shared_rooms for insert to anon, authenticated
with check (trip_code = 'SEOUL630');

drop policy if exists "Anyone can update shared rooms" on public.shared_rooms;
create policy "Anyone can update shared rooms"
on public.shared_rooms for update to anon, authenticated
using (trip_code = 'SEOUL630')
with check (trip_code = 'SEOUL630');

create table if not exists public.shared_checklist (
  id bigint generated by default as identity primary key,
  trip_code text not null default 'SEOUL630',
  item_id text not null,
  completed boolean not null default false,
  updated_by text not null default 'lulu',
  updated_at timestamptz not null default now(),
  unique (trip_code, item_id)
);

alter table public.shared_checklist enable row level security;
alter table public.shared_checklist replica identity full;

drop policy if exists "Anyone can view shared checklist" on public.shared_checklist;
create policy "Anyone can view shared checklist"
on public.shared_checklist for select to anon, authenticated
using (trip_code = 'SEOUL630');

drop policy if exists "Anyone can add shared checklist" on public.shared_checklist;
create policy "Anyone can add shared checklist"
on public.shared_checklist for insert to anon, authenticated
with check (trip_code = 'SEOUL630');

drop policy if exists "Anyone can update shared checklist" on public.shared_checklist;
create policy "Anyone can update shared checklist"
on public.shared_checklist for update to anon, authenticated
using (trip_code = 'SEOUL630')
with check (trip_code = 'SEOUL630');

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'shared_expenses'
  ) then
    alter publication supabase_realtime add table public.shared_expenses;
  end if;
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'shared_plans'
  ) then
    alter publication supabase_realtime add table public.shared_plans;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'shared_rooms'
  ) then
    alter publication supabase_realtime add table public.shared_rooms;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'shared_checklist'
  ) then
    alter publication supabase_realtime add table public.shared_checklist;
  end if;
end $$;

insert into public.shared_expenses (trip_code, title, amount, payer, category, participants, created_at)
select *
from (
  values
    ('SEOUL630', '安国站韩屋民宿', 4680.00, 'lulu', 'lodging', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-02 10:00:00+08'::timestamptz),
    ('SEOUL630', '仁川机场接送', 438.00, 'xiaobei', 'transport', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-08 10:00:00+08'::timestamptz),
    ('SEOUL630', '明洞烤肉预订', 1200.00, 'jiajia', 'food', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-10 10:00:00+08'::timestamptz),
    ('SEOUL630', 'N 首尔塔门票', 516.00, 'ahuang', 'fun', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-11 10:00:00+08'::timestamptz),
    ('SEOUL630', '电话卡 6 张', 288.00, 'anan', 'transport', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-12 10:00:00+08'::timestamptz)
) as seed(trip_code, title, amount, payer, category, participants, created_at)
where not exists (
  select 1 from public.shared_expenses where trip_code = 'SEOUL630'
);

insert into public.shared_rooms (trip_code, room_number, room_type, room_detail, members)
values
  ('SEOUL630', '201', '庭院双床房', '2 张单人床 · 独立卫浴', array['lulu','jiajia']),
  ('SEOUL630', '202', '韩屋榻榻米房', '2 套地铺 · 庭院景观', array['xiaobei','ahuang']),
  ('SEOUL630', '203', '阁楼双人房', '1 张双人床 · 独立卫浴', array['momo','anan'])
on conflict (trip_code, room_number) do nothing;

insert into public.shared_checklist (trip_code, item_id, completed, updated_by)
values
  ('SEOUL630', 'visa', true, 'lulu'),
  ('SEOUL630', 'sim', true, 'lulu'),
  ('SEOUL630', 'cash', true, 'lulu'),
  ('SEOUL630', 'map', false, 'lulu'),
  ('SEOUL630', 'luggage', false, 'lulu')
on conflict (trip_code, item_id) do nothing;
