-- Tripmate 多人共享账单初始化脚本
-- 在 Supabase 项目左侧打开 SQL Editor，粘贴整份脚本，然后点击 Run。

create table if not exists public.shared_expenses (
  id bigint generated by default as identity primary key,
  trip_code text not null default 'SEOUL630',
  title text not null,
  amount numeric(12, 2) not null check (amount > 0),
  payer text not null,
  category text not null check (category in ('lodging', 'food', 'transport', 'fun')),
  participants text[] not null,
  created_at timestamptz not null default now()
);

alter table public.shared_expenses enable row level security;

drop policy if exists "Anyone can view shared trip expenses" on public.shared_expenses;
create policy "Anyone can view shared trip expenses"
on public.shared_expenses for select
to anon, authenticated
using (trip_code = 'SEOUL630');

drop policy if exists "Anyone can add shared trip expenses" on public.shared_expenses;
create policy "Anyone can add shared trip expenses"
on public.shared_expenses for insert
to anon, authenticated
with check (
  trip_code = 'SEOUL630'
  and payer in ('lulu', 'jiajia', 'xiaobei', 'ahuang', 'momo', 'anan')
  and cardinality(participants) > 0
);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'shared_expenses'
  ) then
    alter publication supabase_realtime add table public.shared_expenses;
  end if;
end $$;

insert into public.shared_expenses (trip_code, title, amount, payer, category, participants, created_at)
select *
from (
  values
    ('SEOUL630', '安国站韩屋民宿', 4680.00, 'lulu', 'lodging', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-02 10:00:00+08'::timestamptz),
    ('SEOUL630', '仁川机场接送', 438.00, 'xiaobei', 'transport', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-08 10:00:00+08'::timestamptz),
    ('SEOUL630', '明洞烤肉预订', 1200.00, 'jiajia', 'food', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-10 10:00:00+08'::timestamptz),
    ('SEOUL630', 'N 首尔塔门票', 516.00, 'ahuang', 'fun', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-11 10:00:00+08'::timestamptz),
    ('SEOUL630', '电话卡 6 张', 288.00, 'anan', 'transport', array['lulu','jiajia','xiaobei','ahuang','momo','anan'], '2026-06-12 10:00:00+08'::timestamptz)
) as seed(trip_code, title, amount, payer, category, participants, created_at)
where not exists (
  select 1 from public.shared_expenses where trip_code = 'SEOUL630'
);
